### ISSUE TITLE
npm run build breaks

### ISSUE THREAD

**Issue by oteinone** [Azure-Samples/communication-services-web-calling-hero#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Clone Repository
> 2. run `npm run build`
> 3. Update typescript version to e.g. 3.8.3 to get rid of issues with jest-diff
> 4. run `npm run build again`

### Any log messages given by the failure
> 1: .../node_modules/jest-diff/build/diffLines.d.ts:8:13 - error TS1005: '=' expected
> 2: TypeScript error in .../communication-services-web-calling-hero/Calling/ClientApp/src/containers/GroupCall.ts(39,26):
Property 'streams' does not exist on type 'StreamsState'.
> 3: TypeScript error in .../communication-services-web-calling-hero/Calling/ClientApp/src/core/RemoteStreamSelector.ts(63,20):
Member 'dominantParticipantsCount' implicitly has an 'any' type.

### Expected/desired behavior
> The build is successful

### OS and Version?
> Windows 10

### Versions
> node v15.13.0
> npm 7.7.6

### Mention any other details that might be useful
> After updating typescript version to 3.8.3 and fixing the issues in groupcall.ts and remotestreamselector.ts everything seems to work normally

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alkwa-msft** [comment]
Thanks for finding this I will be fixing this and pushing the fix up so others won't run into this!

**Comment by oteinone** [comment]
Great! I would have made a pull request but I had a bunch of other stuff in the repo, including my connection string ...

**Comment by alkwa-msft** [comment]
thats all good!

should be resolved with abe2a0b
